//1 api 
POST http://localhost:3000/login/
Content-Type: application/json 

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###
//api 2
GET http://localhost:3000/states/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg4Mzk0MTcxfQ.TXOL5eW2Ogs0-A8mYd4YU6HZXKUcdCO6T2wENiUJs4Q


###

//api 3
GET http://localhost:3000/states/8/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg4Mzk0MTcxfQ.TXOL5eW2Ogs0-A8mYd4YU6HZXKUcdCO6T2wENiUJs4Q



###
//api 4
POST http://localhost:3000/districts/
Content-Type: application/json 

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg4Mzk0MTcxfQ.TXOL5eW2Ogs0-A8mYd4YU6HZXKUcdCO6T2wENiUJs4Q


###
//api 5
GET http://localhost:3000/districts/8/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg4Mzk0MTcxfQ.TXOL5eW2Ogs0-A8mYd4YU6HZXKUcdCO6T2wENiUJs4Q

###
//api 6
DELETE  http://localhost:3000/districts/8/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg4Mzk0MTcxfQ.TXOL5eW2Ogs0-A8mYd4YU6HZXKUcdCO6T2wENiUJs4Q

###
//api 7
PUT http://localhost:3000/districts/1/
Content-Type: application/json 

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg4Mzk0MTcxfQ.TXOL5eW2Ogs0-A8mYd4YU6HZXKUcdCO6T2wENiUJs4Q


###
//api 8
GET http://localhost:3000/states/1/stats/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg4Mzk0MTcxfQ.TXOL5eW2Ogs0-A8mYd4YU6HZXKUcdCO6T2wENiUJs4Q



